#pragma once

#define F_CPU 8000000
#define EQ_QUEUE_SIZE 1
#define TM_ALARM_MIN_DELAY 2
#define DEBUG_TRACE_BUFFER_SIZE 0
#define DEBUG_PIN_0_ENABLED 1
#define DEBUG_PIN_1_ENABLED 1
#define DEBUG_PIN_0 PB2
#define DEBUG_PIN_1 PB1
